<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Version>0.0.1</Version>
    <IsPackable>true</IsPackable>
    <PackAsTool>true</PackAsTool>
    <Authors>SKYLAND</Authors>
    <Product>FreeSql</Product>
    <Description>基于FreeSql.Generator二次开发而来，使用 FreeSql 从数据库快速生成LDFCore框架代码，安装：dotnet tool install -g LDFCore.Generator</Description>
    <RepositoryType></RepositoryType>
    <PackageTags>SKYLAND</PackageTags>
    <CopyRazorGenerateFilesToPublishDirectory>true</CopyRazorGenerateFilesToPublishDirectory>
    <Company>SKYLNAD</Company>
    <LangVersion>13</LangVersion>
    <PackageId>MyFreeSql.Generator.Aws</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Temp\**" />
    <Content Remove="Temp\**" />
    <EmbeddedResource Remove="Temp\**" />
    <None Remove="Temp\**" />
    <None Update="Templates\entity.liquid">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\CreateDto.liquid">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\PageInput.liquid">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\PageOutput.liquid">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\UpdateDto.liquid">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Startup.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Templates\controller.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="__razor.cshtml.txt" />
    <None Remove="__重新生成.bat" />
  </ItemGroup>

  

  <ItemGroup>
    <PackageReference Include="Colorful.Console" Version="1.2.15" />
    <PackageReference Include="Fluid.Core" Version="2.24.0" />
    <PackageReference Include="FreeSql.Provider.Dameng" Version="3.5.208" />
    <PackageReference Include="FreeSql.Provider.KingbaseES" Version="3.5.208" />
    <PackageReference Include="FreeSql.Provider.MySqlConnector" Version="3.5.208" />
    <PackageReference Include="FreeSql.Provider.Oracle" Version="3.5.208" />
    <PackageReference Include="FreeSql.Provider.PostgreSQL" Version="3.5.208" />
    <PackageReference Include="FreeSql.Provider.ShenTong" Version="3.5.208" />
    <PackageReference Include="FreeSql.Provider.Sqlite" Version="3.5.208" />
    <PackageReference Include="FreeSql.Provider.SqlServer" Version="3.5.208" />
    <PackageReference Include="RazorEngine.NetCore" Version="3.1.0" />
    <PackageReference Include="Scriban" Version="6.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DmProvider">
      <HintPath>..\Providers\FreeSql.Provider.Dameng\lib\DmProvider\netstandard2.0\DmProvider.dll</HintPath>
    </Reference>
    <Reference Include="System.Data.OscarClient">
      <HintPath>..\Providers\FreeSql.Provider.ShenTong\lib\System.Data.OscarClient.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
